### ISSUE TITLE
通过npm的方式引入到项目里能添加自定义组件吗

### ISSUE THREAD

**Issue by itoip** [Liar0320/lich-form-designer#1]

**Comment by Liar0320** [comment]
[componentsService.registerService(LTextView);](https://github.com/Liar0320/lich-form-designer/blob/542500df2f0150695cfc2f8a3365c525b6507359/src/core/services/index.ts#L5)

[export { lichFormCreator, lichFormParser, ComponentsBaseService, componentsService };](https://github.com/Liar0320/lich-form-designer/blob/542500df2f0150695cfc2f8a3365c525b6507359/src/index.js#L7)

可以   只能做学习用，会有一些bug。
